[package]
name = "drash"
version = "1.9.15"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
chrono = "0.4.39"
clap = { version = "4.5.13", features = ["derive"] }
inquire = "0.7.5"
tabled = "0.16.0"
